package com.easytier.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A6DF5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3E)
val md_theme_light_secondary = Color(0xFF575E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF141B2C)
val md_theme_light_tertiary = Color(0xFF725573)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFDD7FC)
val md_theme_light_onTertiaryContainer = Color(0xFF2A132D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F9FF)
val md_theme_light_onBackground = Color(0xFF1A1C20)
val md_theme_light_surface = Color(0xFFF8F9FF)
val md_theme_light_onSurface = Color(0xFF1A1C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_inverseSurface = Color(0xFF2F3036)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
val md_theme_light_surfaceTint = Color(0xFF1A6DF5)

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002F65)
val md_theme_dark_primaryContainer = Color(0xFF00458E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFBFC6DC)
val md_theme_dark_onSecondary = Color(0xFF293041)
val md_theme_dark_secondaryContainer = Color(0xFF3F4759)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE2F9)
val md_theme_dark_tertiary = Color(0xFFE0BBE0)
val md_theme_dark_onTertiary = Color(0xFF402743)
val md_theme_dark_tertiaryContainer = Color(0xFF593D5A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFDD7FC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E9)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E9)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C20)
val md_theme_dark_inversePrimary = Color(0xFF1A6DF5)
val md_theme_dark_surfaceTint = Color(0xFFADC6FF)

val StatusGreen = Color(0xFF4CAF50)
val StatusRed = Color(0xFFEF5350)
val StatusOrange = Color(0xFFFF9800)
val StatusBlue = Color(0xFF42A5F5)
val StatusPurple = Color(0xFFAB47BC)
val StatusTeal = Color(0xFF26A69A)

val GradientBlueStart = Color(0xFF1A6DF5)
val GradientBlueEnd = Color(0xFF64B5F6)
val GradientDarkStart = Color(0xFF0D47A1)
val GradientDarkEnd = Color(0xFF1976D2)
val GradientGreenStart = Color(0xFF4CAF50)
val GradientGreenEnd = Color(0xFF81C784)
val GradientOrangeStart = Color(0xFFFF9800)
val GradientOrangeEnd = Color(0xFFFFB74D)
